# Configuration preset used on Omu Peregrine.

[game]
# Hub Information
hostname = "[MRP] Omu Peregrine ᴱᵁ⁻ᵂ"
desc = "Come join us on Omu Station! A roleplay-centric game focus with the added chaos of Goob antags and more!"
